name: Cl

on: 

 workflow_dispatch:
   inputs:
      NGROK_AUTHTOKEN:
        description: 'Enter Your Ngrok Authtoken'
        required: true
      ADD_USER:
        description: 'Enter Your Username'
        required: true
      USER_PASSWD:
        description: 'Enter Your Password'
        required: true

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Downloading Files
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Extract
      run: Expand-Archive ngrok.zip
