name: Cl

on: 

 workflow_dispatch:
   inputs:
      NGROK_AUTHTOKEN:
        description: 'Enter Your Ngrok Authtoken'
        required: true
      NGROK_REGION:
        description: 'Enter Ngrok Region You Want (us,eu,ap,au,jp)'
        required: true
      ADD_USER:
        description: 'Enter Your Username'
        required: true
      USER_PASSWD:
        description: 'Enter Your Password (ex: @YourPassword'
        required: true

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Downloading Files.
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/xssdro/TEstVM/main/files/wallpaper.bat -OutFile wallpaper.bat
        Invoke-WebRequest https://raw.githubusercontent.com/xssdro/TEstVM/main/files/wallpaper.png -OutFile wallpaper.bmp
        Invoke-WebRequest https://raw.githubusercontent.com/xssdro/TEstVM/main/files/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/xssdro/TEstVM/main/files/login.bat -OutFile login.bat
    - name: Extracting Files.
      run: Expand-Archive ngrok.zip
    - name: Connecting To Your Ngrok Account.
      run: .\ngrok\ngrok.exe authtoken $Env:Authtoken
      env:
        Authtoken: ${{ github.event.inputs.NGROK_AUTHTOKEN }}
    - name: Activating Your RDP Acces
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        copy wallpaper.bmp D:\a\wallpaper.bmp
        copy wallpaper.bat D:\a\wallpaper.bat
    - name: Creating Windows Account.
      run: |
        $Password = ConvertTo-SecureString "$Env:PASSWD" –AsPlainText –Force
        New-LocalUser "$Env:USERNAME" -Password $Password -AccountNeverExpires -PasswordNeverExpires -FullName "$Env:USERNAME" -Description "none"
        Add-LocalGroupMember -Group "Administrators" -Member "$Env:USERNAME"
      env:
        USERNAME: ${{ github.event.inputs.ADD_USER }}
        PASSWD: ${{ github.event.inputs.USER_PASSWD }}
    - name: Creating Ngrok Tunnel.
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp -region $Env:region 3389"'
      env:
        region: ${{ github.event.inputs.NGROK_REGION }}
    - name: Connecting RDP.
      run: cmd /c start.bat
    - name: Fetching Login Data.
      run: cmd /c login.bat
    - name: RDP Succesfully Created | Enjoy Your RDP.
      run: |
        Invoke-WebRequest https://github.com/xssdro/TEstVM/raw/main/files/timeout.ps1 -OutFile timeout.ps1
        ./timeout.ps1
