name: CI

on:
  workflow_dispatch:
    inputs:
      authtoken:
        description: 'NGROK AUTH TOKEN'
        required: true
      username:
        description: 'USERNAME'
        required: true
      password:
        description: 'PASSWORD'
        required: true
  
  
jobs:
  builds:
  
    runs-on: windows-latest
    timeout-minutes: 9999
    
    steps:
    - name: Downloading important file...
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Extracting File...
      run: Expand-Archive ngrok.zip
    - name: Connecting to your ngrok account...
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ github.events.inputs.authtoken }}
    - name: Activating your RDP access...
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1


    - name: Creating ngrok tunnel...
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp 3389"'
    - name: Connecting...
      run: |
       @echo off
       del /f "C:\Users\Public\Desktop\Epic Games Launcher.lnk" > out.txt 2>&1
       net config server /srvcomment:"Windows Server 2019 By ExDeus Arch" > out.txt 2>&1
       REG ADD "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer" /V EnableAutoTray /T REG_DWORD /D 0 /F > out.txt 2>&1
       REG ADD "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run" /f /v Wallpaper /t REG_SZ /d D:\a\wallpaper.bat
       net user ${{ github.events.inputs.username }} ${{ github.events.inputs.password }}/add >nul
       net localgroup administrators administrator /add >nul
       net user ${{ github.events.inputs.username }} /active:yes >nul
       net user installer /delete
       diskperf -Y >nul
       sc config Audiosrv start= auto >nul
       sc start audiosrv >nul
       ICACLS C:\Windows\Temp /grant ${{ github.events.inputs.username }}:F >nul
       ICACLS C:\Windows\installer /grant ${{ github.events.inputs.username }}:F >nul
       echo =============================
       echo Task Completed, if your RDP offline or dead you can try re-build it again.
    - name: Fetching login information...
      run: |
        @echo off
        echo ======================
        echo RDP Windows Server 2019
        echo RAM: 7 GB
        echo SSD: 255 GB
        echo .
        echo ======================
        echo === RDP INFO LOGIN ===
        echo ======================
        echo .
        echo .
        echo .
        echo ========= IP Address =========
        tasklist | find /i "ngrok.exe" >Nul && curl -s localhost:4040/api/tunnels | jq -r .tunnels[0].public_url || echo "Tidak bisa mendapatkan NGROK tunnel, pastikan NGROK_AUTH_TOKEN benar di Settings> Secrets> Repository secret. Mungkin VM Anda sebelumnya masih berjalan: https://dashboard.ngrok.com/status/tunnels "
        echo ======================
        echo .
        echo .
        echo .
        echo Username: ${{ github.events.inputs.username }}
        echo Password: ${{ github.events.inputs.password }}
        echo .
        echo ======================
        echo === RDP INFO LOGIN ===
        echo ======================
        echo You can log in to your RDP now!
        ping -n 10 127.0.0.1 >nul
    - name: RDP succesfully created | Windows Server 2019 by Exdeus Arch
      run: ./timeout.ps1

